### PR TITLE
hardware_notes: update README.md

### PR DESCRIPTION
**Pull request by uis246**

### CODE REVIEW

**Comment by gamelaster** [comment]
@uis246 there is some problem with your edit. Take look on CI.

**Comment by uis246** [comment]
> @uis246 there is some problem with your edit. Take look on CI.

```
rm: cannot remove '../../html': No such file or directory
rm: cannot remove '../../docs': No such file or directory
```

**Comment by gamelaster** [comment]
@uis246 no. This is problem:
```
/home/runner/work/bl602-docs/bl602-docs/src/en/Examples/demo_protocols_http/http.rst:7:Title underline too short.
```
What is not your fault, I'm gonna check.

**Comment by gamelaster** [comment]
Fixed in repo. If @tchebb agrees with changes, then we can merge it.

**Comment by tchebb** [comment]
Looks good to me. Thanks!

**Review by tchebb — APPROVED** [review]

**Pull request merged**
