### PR TITLE
English docs for Development Environment and Quickstart

### PR DESCRIPTION
**Pull request by xkxx**
Hi Pine64 maintainers,

This PR contains translated and fat-trimmed English documentations for sections `Development Environment` and `Quickstart`. I was unsure where to start contributing to the effort and I don't have a dev board to test with, so I thought I would start with the docs. Let me know if this is helpful at all and whether I should continue with more of this.

Thanks,

xkxx

### CODE REVIEW

**Comment by gamelaster** [comment]
Thank you very much for your pull request!
I think it's definitely helpful for new-comers. If you want, you can continue, or you can just wait for your EVB and then contribute to core. Once again, thank you very much and sign up for free EVB :) .

For receiving the free PineCone, please sign up at [this link](https://nutcracker.pine64.org/free-evb/).
(If there will be any issues with signing up, please let me know here).

**Comment by xkxx** [comment]
Thanks for the lightning-fast code review! Excited about getting my hands on the EVB :)

**Comment by AndreasVerden** [comment]
@xkxx, I have noticed missing images in the linux quickstart guide and wasn't able to fix the issue myself.
I did commit some progress on my [fork](https://github.com/SimonKindhauser/bl602-docs/commit/1d946efbe4f09eed7aa7fa24bcb0c9eb3cd383bc)

Have you forgotten to push the images?

**Comment by xkxx** [comment]
@SimonKindhauser This issue existed before my PR - I suspect the image paths got messed up during import. I'll work on addressing that.

**Pull request merged**
